language: c
os:
  - linux
  - osx
addons:
    apt:
        sources:
          - sourceline: ppa:plt/racket
        packages:
          - racket
before_install:
  - if [ "$TRAVIS_OS_NAME" == osx ]; then brew cask install racket; fi
script:
  - raco test tests
notifications:
    email: false
